-  name:  Add sonarqube user
   ansible.builtin.user:
     name: sonarqube


-  name: download sonarqube
   ansible.builtin.unarchive:
     src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.4.1.88267.zip
     dest: /home/sonarqube
     remote_src: yes
     owner: sonarqube
     group: sonarqube



-  name: install java
   ansible.builtin.dnf:
     name: java-17-openjdk.x86_64
     state: installed


-  name: copy sonarqube service file
   ansible.builtin.template:
     src: sonarqube.service
     dest: /etc/systemd/system/sonarqube.service


-  name: start sonarqube service
   ansible.builtin.systemd_service:
     name: sonarqube
     state: started
     enabled:  yes


