-  name:  Add sonarqube user
   ansible.builtin.user:
     name: sonarqube


-  name: download sonarqube
   ansible.builtin.unarchive:
     src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.4.1.88267.zip
     dest: /home/sonarqube
     remote_src: yes

