-  name: Download Alert Manager
   ansible.builtin.unarchive:
     src: https://github.com/prometheus/alertmanager/releases/download/v{{alertmanager_version}}/alertmanager-{{alertmanager_version}}.linux-amd64.tar.gz
     dest: /opt
     remote_src: true

-  name: copy alertmanager service file
   ansible.builtin.template:
     src: alertmanager.service
     dest: /etc/systemd/system/alertmanager.service



-  name: copy alertmanager server configuration
   ansible.builtin.template:
     src: alertmanager.yml
     dest: /opt/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager.yml



-  name: start alertmanager service
   ansible.builtin.systemd:
     name: alertmanager
     state: started
     enabled: yes
     daemon-reload: yes