-  name: copy jenkins repo file
   ansible.builtin.template:
     src: jenkins.repo
     dest: /etc/yum.repos.d/jenkins.repo


-  name: install jenkins
   ansible.builtin.dnf:
     name:
       -  fontconfig
       -  java-17-openjdk
       -  jenkins
     state: installed


-  name: start jenkins
   ansible.builtin.systemd_service:
     name: jenkins
     state: started
     enabled: yes


-  name: Create Multi Branch Pipeline Jobs
   community.general.jenkins_job:
     config: "{{ lookup('template', 'templates/multibranch.xml') }}"
     name: "{{item}}"
     password: admin123
     url: http://jenkins-internal.madhanmohanreddy.tech:8080
     user: admin
   loop:
     - frontend
     - catalogue
     - user
     - cart
     - payment
     - shipping
     - parameter-store-init-container-image
     - schema-loader



#-  name: Create job
#   community.general.jenkins_job:
#     config: "{{ lookup('template', 'templates/pipeline.xml') }}"
#     name: "{{item}}"
#     password: admin123
#     url: http://jenkins-internal.madhanmohanreddy.tech:8080
#     user: admin
#   loop:
#     - frontend
#     - catalogue
#     - user
#     - cart
#     - payment
#     - shipping
#     - dispatch
#     - parameter-store-init-container-image
#     - schema-loader



