-  name: copy jenkins repo file
   ansible.builtin.template:
     src: jenkins.repo
     dest: /etc/yum.repos.d/jenkins.repo


-  name: install jenkins
   ansible.builtin.dnf:
     name:
       -  fontconfig
       -  java-17-openjdk
       -  jenkins
     state: installed


-  name: start jenkins
   ansible.builtin.systemd_service:
     name: jenkins
     state: started
     enabled: yes



- name: Create job
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/pipeline.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://jenkins-internal.madhanmohanreddy.tech:8080
    user: admin
  loop:
    - frontend



