-  name: download prometheus
   ansible.builtin.unarchive:
     src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
     dest: /opt
     remote_src: true


-  name: copy prometheus service file
   ansible.builtin.template:
     src: prometheus.service
     dest: /etc/systemd/system/prometheus.service



- name: copy prometheus server configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-{{ prometheus_version}}.linux-amd64/prometheus.yml


- name: copy prometheus alerts configuration
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus-{{prometheus_version}}.linux-amd64/alerts.yml


-  name: start prometheus service
   ansible.builtin.systemd:
     name: prometheus
     state: restarted
     enabled: yes
     daemon-reload: yes


