-  name: set-hostname
   ansible.builtin.shell: set-hostname elasticsearch

-  name: copy elasticsearch repo file
   ansible.builtin.template:
     src: elastic.repo
     dest: /etc/yum.repos.d/elastic.repo


-  name: install ELK Stack
   ansible.builtin.dnf:
     name: "{{item}}"
     state: installed
   loop:
     -  elasticsearch
     -  kibana
     -  logstash
     -  nginx


-  name: copy the nginx config file
   ansible.builtin.template:
     src: nginx.conf
     dest: /etc/nginx/nginx.conf


-  name: copy the logstash config file
   ansible.builtin.template:
     src: logstash.conf
     dest: /etc/logstash/conf.d/logstash.conf


-  name: start ELK Stack
   ansible.builtin.systemd_service:
     name: "{{item}}"
     state: restarted
     enabled: yes
   loop:
     -  elasticsearch
     -  kibana
     -  logstash
     -  nginx

-  name: install filebeat
   ansible.builtin.dnf:
     name: filebeat
     state: installed


-  name: filebeat config update
   ansible.builtin.template:
     src: filebeat.yml
     dest: /etc/filebeat/filebeat.yml


-  name: start filebeat
   ansible.builtin.systemd_service:
     name: filebeat
     state: restarted


-  name: configure syslog
   ansible.builtin.template:
     src: rsyslog.conf
     dest: /etc/rsyslog.d/{{component}}.conf


-  name: restart rsyslog
   ansible.builtin.systemd_service:
     name: rsyslog
     state: restarted










